[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000228D95F1090>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/203d0e80-b6af-4b9a-b3d7-f385eebdca31
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000228D95F1310>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/203d0e80-b6af-4b9a-b3d7-f385eebdca31
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000228D9520FC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/203d0e80-b6af-4b9a-b3d7-f385eebdca31