[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B2FC448F50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/3545803c-a80f-4e17-a51c-2856ce38e753
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B2FC4491D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/3545803c-a80f-4e17-a51c-2856ce38e753
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B2FC325350>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/3545803c-a80f-4e17-a51c-2856ce38e753