[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CD0A09D090>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/4b48f16f5cc8acdfe05c997bd619df3e
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CD0A09D310>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/4b48f16f5cc8acdfe05c997bd619df3e
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CD0A0049D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/4b48f16f5cc8acdfe05c997bd619df3e