[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000230B3C03C50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/dcfd939e6f86084b4dbd9c31f9be7b5d
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000230B3C03ED0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/dcfd939e6f86084b4dbd9c31f9be7b5d
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000230B3ABFE10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/dcfd939e6f86084b4dbd9c31f9be7b5d