[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000225E8293C50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/0f5d2cf6-6109-4bc8-8f7b-496e2a296dbe
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000225E8293ED0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/0f5d2cf6-6109-4bc8-8f7b-496e2a296dbe
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000225E83283E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/0f5d2cf6-6109-4bc8-8f7b-496e2a296dbe