[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015AB70CFB10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/faa3c5f8-311f-4e6b-ad30-1bcd84619de3
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015AB70CFD90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/faa3c5f8-311f-4e6b-ad30-1bcd84619de3
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015AB71602B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/faa3c5f8-311f-4e6b-ad30-1bcd84619de3