[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000273A972FB10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/83f832258fbd09464299f30a39ab62f3
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000273A972FD90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/83f832258fbd09464299f30a39ab62f3
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000273A91ADE00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/83f832258fbd09464299f30a39ab62f3