[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001902FD43C50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e92e20c111c69b1601bbcde38e118af0
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001902FD43ED0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e92e20c111c69b1601bbcde38e118af0
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001902F88FE10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e92e20c111c69b1601bbcde38e118af0