[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002EA0C8F3C50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/15492325-4f12-40ed-adf1-f80ea6256d09
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002EA0C8F3ED0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/15492325-4f12-40ed-adf1-f80ea6256d09
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002EA0CD643E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/15492325-4f12-40ed-adf1-f80ea6256d09