[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000271F7FDFB10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/800276e8fb79a7846323c495bf23ec7e
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000271F7FDFD90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/800276e8fb79a7846323c495bf23ec7e
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000271F7AFDE00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/800276e8fb79a7846323c495bf23ec7e