[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020D72D63C50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/fab3edbf-9d84-4243-9e84-a59efad79056
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020D72D63ED0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/fab3edbf-9d84-4243-9e84-a59efad79056
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020D72DF43E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/fab3edbf-9d84-4243-9e84-a59efad79056