[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019B78313C50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ce8bf624-0e37-4c11-b3fa-76d23cf33892
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019B78313ED0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ce8bf624-0e37-4c11-b3fa-76d23cf33892
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019B783A43E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ce8bf624-0e37-4c11-b3fa-76d23cf33892