[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024BF7753C50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/6da3baf377ed922dd5662c12adb7b10a
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024BF7753ED0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/6da3baf377ed922dd5662c12adb7b10a
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024BF72C3E10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/6da3baf377ed922dd5662c12adb7b10a